name: super_easy_in_app_purchase_example
description: Demonstrates how to use the super_easy_in_app_purchase plugin.

publish_to: 'none'

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Make sure to always use the latest version
  super_easy_in_app_purchase: ^0.2.1

flutter:
  uses-material-design: true
